import { ArrowUpRight, ChevronDown, ExternalLink, FolderCode } from 'lucide-react'
import { useState } from 'react'
import { projects } from '../data/projects'

const filters = ['All', 'Cybersecurity', 'AI / ML', 'Web', 'Cloud', 'Automation']
export function Projects() {
  const [filter, setFilter] = useState('All')
  const [expanded, setExpanded] = useState<string | null>(null)
  const shown = projects.filter((project) => filter === 'All' || project.category.toLowerCase().includes(filter.toLowerCase().replace(' / ml', '')) || (filter === 'Web' && project.category.toLowerCase().includes('frontend')))
  return <section id="projects" className="section-pad projects-section"><div className="section-heading"><div><p className="section-kicker">03 / selected work</p><h2>Built to be <em>useful.</em></h2></div><p>Experiments and systems shaped around real problems, measured thinking and a bias toward making.</p></div><div className="filter-row" role="group" aria-label="Filter projects">{filters.map((item) => <button key={item} className={filter === item ? 'filter active' : 'filter'} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="project-list">{shown.map((project) => <article className="project-card" key={project.number}><div className="project-number">{project.number}</div><div className="project-main"><div className="project-title-row"><div><p className="project-category">{project.category}</p><h3>{project.name}</h3></div><a className="round-link" href="#contact" aria-label={`Discuss ${project.name}`}><ArrowUpRight size={19} /></a></div>{project.context && <p className="project-context">{project.context}</p>}<p className="project-description">{project.description}</p><div className="tag-list project-tags">{project.technologies.slice(0, 7).map((tech) => <span key={tech}>{tech}</span>)}</div>{expanded === project.number && project.features && <div className="feature-list"><strong>System features</strong>{project.features.map((feature) => <span key={feature}><span className="live-dot" />{feature}</span>)}</div>}<button className="details-button" onClick={() => setExpanded(expanded === project.number ? null : project.number)}>{expanded === project.number ? 'Hide details' : project.features ? 'Explore details' : 'Project notes'} <ChevronDown className={expanded === project.number ? 'rotate' : ''} size={15} /></button></div><div className="project-mark"><FolderCode size={23} /><span>PROJECT<br />{project.number}</span></div></article>)}</div><div className="project-footnote"><ExternalLink size={15} /> GitHub project links will be added as repositories are made public.</div></section>
}